### ISSUE TITLE
msgpack requirement fails on older versions

### ISSUE THREAD

**Issue by andrew-vant** [racker/eom#82]
requirements.txt line 3 doesn't specify a minimum version of python-msgpack. 0.4.6 works, 0.3.0 throws an exception when importing eom:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 473, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 115, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 33, in load
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 362, in import_app
    __import__(module)
  File "/opt/rse/rse.py", line 29, in <module>
    from eom import auth
  File "/usr/local/lib/python2.7/dist-packages/eom/auth.py", line 140, in <module>
    __packer = msgpack.Packer(encoding='utf-8', use_bin_type=True)
  File "_packer.pyx", line 77, in msgpack._packer.Packer.__init__ (msgpack/_packer.cpp:77)
TypeError: __init__() got an unexpected keyword argument 'use_bin_type'
```

No idea what the actual minimum version needed is, sorry. Presumably it's whenever the use_bin_type argument was added to msgpack.Packer.

**Comment by BenjamenMeyer** [comment]
We can probably just require that it be 0.4.6 and higher; I don't think there was ever a specific version intended.
